language: java
# 脚本
script: "mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V && mvn deploy -Dregistry=https://maven.pkg.github.com/superzhc -Dtoken=${API_KEY}"
# 缓存 Maven 本地仓库
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master
